name: Shippie 🚢
on:
  pull_request:
    branches: [main]
jobs:
  run_code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Shippie 🚢
        uses: mattzcarey/shippie@v0.10.0
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MODEL_STRING: "anthropic:claude-sonnet-4-20250514"
          CUSTOM_INSTRUCTIONS: |
              Focus on iOS/Swift best practices including:
              - Memory management and retain cycles
              - Multithreading
              - SwiftUI patterns
              - iOS architectural patterns MVVM and Solid Principles
              - Xcode project structure
              - SPM dependency management
