name: Manual App Distribution
on:
  workflow_dispatch:
    inputs:
      distribution_platform:
        description: 'Choose distribution platform'
        required: true
        type: choice
        options:
          - firebase
          - testflight
        default: 'firebase'
      release_notes:
        description: 'Release notes (optional)'
        required: false
        type: string

jobs:
  distribute:
    name: Distribute App
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'
          
      - name: Install Fastlane
        run: gem install fastlane

      - name: Setup Firebase CLI
        if: ${{ github.event.inputs.distribution_platform == 'firebase' }}
        run: |
          curl -sL https://firebase.tools | bash

      - name: Setup certificates and provisioning profiles
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          fastlane fetch_provisioning_profile

      - name: Deploy to Firebase
        if: ${{ github.event.inputs.distribution_platform == 'firebase' }}
        run: |
          if [ -n "${{ github.event.inputs.release_notes }}" ]; then
            fastlane deploy_staging release_notes:"${{ github.event.inputs.release_notes }}"
          else
            fastlane deploy_staging
          fi

      - name: Deploy to TestFlight
        if: ${{ github.event.inputs.distribution_platform == 'testflight' }}
        run: fastlane deploy_production
